//! v1.8 Phase 2-D — Email source (IMAP digest).
//!
//! Pulls recent inbox messages from Gmail / Outlook over IMAPS (993),
//! groups them by thread (normalised subject + reply chain), and writes
//! one atom per thread to `~/.tangerine-memory/threads/email/`.
//!
//! Design notes
//! ============
//!
//! * **Auth**: app password (Gmail / Outlook MS-account "App password" UI).
//!   The `EmailConfig.app_password` arrives over IPC, gets stored in the
//!   OS keychain via `commands::sync::TokenStore` keyed on the username.
//!   We never round-trip the secret to the React layer — the frontend only
//!   sends it once, then references the username. Same model as the
//!   GitHub OAuth token store.
//!
//! * **IMAP crate**: `imap` 3.0 with `native-tls`. Blocking interface
//!   wrapped in `tokio::task::spawn_blocking` so the runtime stays free
//!   for IPC. No async-imap — the blocking surface is well-trodden, the
//!   per-fetch overhead is negligible compared to the IMAP server's own
//!   round-trip latency.
//!
//! * **Threading**: we group by `subject_root` (subject with leading
//!   `Re:` / `Fwd:` / `回复:` / `[Tag]` prefixes stripped, lowercased) plus
//!   the In-Reply-To / References chain. Two messages whose normalised
//!   subjects match OR whose Message-IDs link via References are placed
//!   in the same thread. This is an approximation of Gmail's algorithm —
//!   good enough for the digest; the user can split threads manually by
//!   editing the atom file.
//!
//! * **Atom shape**: `~/.tangerine-memory/threads/email/{thread-slug}.md`.
//!   Slug = first 40 chars of the subject root, slugified. Frontmatter:
//!   `subject`, `participants`, `last_message_at`, `source: email`,
//!   `message_ids`, `provider`. Body = chronological message digest with
//!   one paragraph per message (sender, ts, first 800 chars of body).
//!
//! * **Dedup**: rerunning `fetch_recent` doesn't write duplicates. We
//!   merge new messages into the existing atom by reading its
//!   `message_ids:` frontmatter line and skipping IDs we've already
//!   recorded. The fetch tracks per-thread dirty bits so we only rewrite
//!   atoms whose content actually changed.
//!
//! * **Tests**: an `ImapStream` trait abstraction lets unit tests stub the
//!   network. Real production uses `imap::Session<TlsStream<TcpStream>>`;
//!   tests use a `FakeImapStream` that yields canned message bodies.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use tauri::State;

use crate::commands::sync::TokenStore;
use crate::commands::{AppError, AppState};

// ---------------------------------------------------------------------------
// Public config shape — mirrored on the React side.

/// Provider tag drives the IMAP host + port defaults. We keep the shape open
/// (string, not enum) so a future "imap" / "fastmail" / "yahoo" entry doesn't
/// require a Rust schema bump.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct EmailConfig {
    /// "gmail" | "outlook" | "imap" (custom). Anything else is rejected.
    pub provider: String,
    /// Email address — also doubles as the IMAP login on both Gmail and
    /// Outlook.
    pub username: String,
    /// App password (NOT the user's primary password). Generated by the
    /// user from their Google / Microsoft account settings. Stored via
    /// `TokenStore` keyed on `username`; not echoed back over IPC after
    /// the initial set.
    #[serde(default)]
    pub app_password: Option<String>,
    /// How far back to fetch. Hard-cap at 30 to keep first-run wait time
    /// bounded; the daemon's daily heartbeat means a missed window
    /// catches up within 24 h regardless.
    #[serde(default = "default_lookback_days")]
    pub fetch_lookback_days: u32,
    /// Optional override — when set, skips the provider lookup. Used for
    /// custom IMAP servers and for tests.
    #[serde(default)]
    pub host: Option<String>,
    #[serde(default)]
    pub port: Option<u16>,
}

fn default_lookback_days() -> u32 {
    7
}

impl EmailConfig {
    /// Resolve `(host, port)` for the given provider. Rejects unknown
    /// provider strings unless `host` is explicitly set.
    pub fn imap_endpoint(&self) -> Result<(String, u16), AppError> {
        if let (Some(h), Some(p)) = (&self.host, self.port) {
            return Ok((h.clone(), p));
        }
        match self.provider.as_str() {
            "gmail" => Ok(("imap.gmail.com".to_string(), 993)),
            "outlook" => Ok(("outlook.office365.com".to_string(), 993)),
            "imap" => self
                .host
                .clone()
                .map(|h| (h, self.port.unwrap_or(993)))
                .ok_or_else(|| {
                    AppError::user(
                        "imap_host_missing",
                        "host is required when provider == 'imap'",
                    )
                }),
            other => Err(AppError::user(
                "unknown_provider",
                format!("unknown email provider: {other}"),
            )),
        }
    }

    pub fn keyring_login(&self) -> String {
        format!("email:{}", self.username)
    }
}

// ---------------------------------------------------------------------------
// Atom shape

/// One message lifted from IMAP. Crate-internal — flattened into the atom
/// body when we write to disk.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct EmailMessage {
    pub message_id: String,
    pub subject: String,
    pub from: String,
    pub to: Vec<String>,
    pub cc: Vec<String>,
    /// RFC 3339. We accept whatever mailparse hands back; bad dates fall
    /// through to "now" so the atom still gets a sortable timestamp.
    pub date: String,
    pub body: String,
    /// Parsed `In-Reply-To` + `References` headers, deduped. Used for
    /// threading.
    pub references: Vec<String>,
}

/// Thread = one or more messages sharing a subject root (or chained via
/// References). The atom file is named after the thread.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
pub struct EmailThread {
    pub subject_root: String,
    pub messages: Vec<EmailMessage>,
}

impl EmailThread {
    pub fn participants(&self) -> Vec<String> {
        let mut set: BTreeSet<String> = BTreeSet::new();
        for m in &self.messages {
            if !m.from.is_empty() {
                set.insert(m.from.clone());
            }
            for t in &m.to {
                set.insert(t.clone());
            }
            for c in &m.cc {
                set.insert(c.clone());
            }
        }
        set.into_iter().collect()
    }

    pub fn last_message_at(&self) -> Option<&str> {
        self.messages.last().map(|m| m.date.as_str())
    }

    pub fn slug(&self) -> String {
        slugify_subject(&self.subject_root)
    }
}

// ---------------------------------------------------------------------------
// Subject normalisation + slugification

/// Strip leading reply / forward markers and bracketed tags so two messages
/// in the same thread land on the same key. Lowercases the result.
///
/// Examples:
///   "Re: [Eng] OKRs"     -> "okrs"
///   "Fwd: Re: meeting"   -> "meeting"
///   "回复: 项目计划"      -> "项目计划"
pub fn normalise_subject(raw: &str) -> String {
    let mut s = raw.trim().to_string();
    let prefixes = [
        "re:", "fw:", "fwd:", "回复:", "回复：", "答复:", "答复：",
        "antwort:", "rép:", "ответ:",
    ];
    let mut changed = true;
    while changed {
        changed = false;
        let lower = s.to_lowercase();
        for p in prefixes {
            if let Some(rest) = lower.strip_prefix(p) {
                let cut = s.len() - rest.len();
                s = s[cut..].trim_start().to_string();
                changed = true;
                break;
            }
        }
        // Strip a single leading `[bracket tag]` group.
        if s.starts_with('[') {
            if let Some(end) = s.find(']') {
                if end + 1 < s.len() {
                    s = s[end + 1..].trim_start().to_string();
                    changed = true;
                }
            }
        }
    }
    s.trim().to_lowercase()
}

/// Ascii-fold + lowercase + dash. Capped at 40 visible chars so the file
/// name stays human-readable on Windows (which doesn't love 200-char
/// paths).
pub fn slugify_subject(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut last_dash = true;
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
            last_dash = false;
        } else if c.is_alphanumeric() {
            // Keep non-ASCII letters (Chinese, etc.) verbatim — Windows
            // handles UTF-8 file names since 1909+.
            out.push(c);
            last_dash = false;
        } else if !last_dash {
            out.push('-');
            last_dash = true;
        }
    }
    let trimmed = out.trim_matches('-').to_string();
    if trimmed.is_empty() {
        return "untitled".to_string();
    }
    // Cap at 40 chars so the resulting filename + ".md" stays readable.
    let mut buf = String::new();
    let mut count = 0;
    for c in trimmed.chars() {
        if count >= 40 {
            break;
        }
        buf.push(c);
        count += 1;
    }
    buf.trim_end_matches('-').to_string()
}

// ---------------------------------------------------------------------------
// Atom write — frontmatter + body assembly

/// Build the full markdown body for a thread atom. Pure function — tests
/// assert on this directly without touching the filesystem.
pub fn build_email_atom(thread: &EmailThread, provider: &str) -> String {
    let participants = thread.participants();
    let last = thread.last_message_at().unwrap_or("");
    let subject = thread
        .messages
        .first()
        .map(|m| m.subject.clone())
        .unwrap_or_else(|| thread.subject_root.clone());
    let mut message_ids: Vec<String> = thread
        .messages
        .iter()
        .map(|m| m.message_id.clone())
        .filter(|id| !id.is_empty())
        .collect();
    message_ids.sort();
    message_ids.dedup();

    let mut out = String::new();
    out.push_str("---\n");
    out.push_str(&format!("source: email\n"));
    out.push_str(&format!("provider: {}\n", yaml_scalar(provider)));
    out.push_str(&format!("subject: {}\n", yaml_scalar(&subject)));
    out.push_str("participants:\n");
    for p in &participants {
        out.push_str(&format!("  - {}\n", yaml_scalar(p)));
    }
    out.push_str(&format!("last_message_at: {}\n", yaml_scalar(last)));
    out.push_str("message_ids:\n");
    for id in &message_ids {
        out.push_str(&format!("  - {}\n", yaml_scalar(id)));
    }
    out.push_str("---\n\n");

    out.push_str(&format!("# {}\n\n", subject));
    for m in &thread.messages {
        out.push_str(&format!(
            "## {} — {}\n\n",
            if m.from.is_empty() { "(unknown)" } else { &m.from },
            if m.date.is_empty() { "—" } else { &m.date },
        ));
        let truncated: String = m.body.chars().take(800).collect();
        out.push_str(truncated.trim());
        out.push_str("\n\n");
    }
    out
}

/// Quote a YAML scalar value safely. We intentionally keep this minimal —
/// the schema is small and the strings are constrained (no embedded
/// newlines after our own normalisation).
fn yaml_scalar(s: &str) -> String {
    let needs_quote = s.is_empty()
        || s.contains(':')
        || s.contains('#')
        || s.contains('\n')
        || s.starts_with('-')
        || s.starts_with(' ')
        || s.ends_with(' ');
    if needs_quote {
        let escaped = s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n");
        format!("\"{}\"", escaped)
    } else {
        s.to_string()
    }
}

/// Read the existing atom (if present) and return the set of `message_ids`
/// already recorded. Used for dedup so re-fetching doesn't bloat the atom.
pub fn read_existing_message_ids(path: &Path) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let raw = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(_) => return out,
    };
    // Find the message_ids: section in the frontmatter.
    let mut in_block = false;
    let mut in_ids = false;
    for line in raw.lines() {
        if line.trim() == "---" {
            in_block = !in_block;
            if !in_block {
                break;
            }
            continue;
        }
        if !in_block {
            continue;
        }
        if line.trim_start().starts_with("message_ids:") {
            in_ids = true;
            continue;
        }
        if in_ids {
            if let Some(rest) = line.trim_start().strip_prefix("- ") {
                let id = rest.trim().trim_matches('"').trim_matches('\'').to_string();
                if !id.is_empty() {
                    out.insert(id);
                }
                continue;
            }
            // Hit the next key — done.
            if line.starts_with(|c: char| !c.is_whitespace()) {
                in_ids = false;
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// IMAP fetch — generic over the stream so tests can stub.

/// Minimal IMAP surface we depend on. Lets `fetch_recent_with_stream` take
/// either a real `imap::Session` (production) or a `FakeImapStream` (tests).
pub trait ImapStream {
    /// Select the INBOX. Returns the highest UID currently in the box.
    fn select_inbox(&mut self) -> Result<u32, String>;
    /// Fetch raw RFC 822 bodies for messages whose internal date is on or
    /// after `since`. Each entry is `(uid, body_bytes)`.
    fn fetch_since(&mut self, since: DateTime<Utc>) -> Result<Vec<(u32, Vec<u8>)>, String>;
    /// Close the session. Best-effort.
    fn logout(&mut self);
}

/// Parse one RFC 822 body into our `EmailMessage`. Tolerant — bad dates,
/// missing fields, or mailparse errors fall back to safe defaults so the
/// thread group still lands.
pub fn parse_rfc822(raw: &[u8]) -> Result<EmailMessage, String> {
    let parsed = mailparse::parse_mail(raw).map_err(|e| format!("parse: {e}"))?;
    let headers = &parsed.headers;
    let lookup = |key: &str| {
        headers
            .iter()
            .find(|h| h.get_key().eq_ignore_ascii_case(key))
            .map(|h| h.get_value())
            .unwrap_or_default()
    };
    let message_id = lookup("Message-ID")
        .trim()
        .trim_start_matches('<')
        .trim_end_matches('>')
        .to_string();
    let subject = lookup("Subject");
    let from = lookup("From");
    let to: Vec<String> = lookup("To")
        .split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect();
    let cc: Vec<String> = lookup("Cc")
        .split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect();
    let date_raw = lookup("Date");
    let date = mailparse::dateparse(&date_raw)
        .ok()
        .and_then(|secs| chrono::DateTime::<Utc>::from_timestamp(secs, 0))
        .map(|dt| dt.to_rfc3339())
        .unwrap_or_else(|| Utc::now().to_rfc3339());

    let mut references: Vec<String> = Vec::new();
    for (key, _) in [("In-Reply-To", ()), ("References", ())] {
        let raw = lookup(key);
        for tok in raw.split_whitespace() {
            let cleaned = tok.trim().trim_start_matches('<').trim_end_matches('>');
            if !cleaned.is_empty() {
                references.push(cleaned.to_string());
            }
        }
    }
    references.sort();
    references.dedup();

    let body = first_text_body(&parsed).unwrap_or_default();

    Ok(EmailMessage {
        message_id,
        subject,
        from,
        to,
        cc,
        date,
        body,
        references,
    })
}

/// Pull the first text/plain body (fall back to text/html stripped to
/// plain). Recurses through MIME parts.
fn first_text_body(part: &mailparse::ParsedMail) -> Option<String> {
    let ctype = part.ctype.mimetype.to_lowercase();
    if ctype == "text/plain" {
        return part.get_body().ok();
    }
    if ctype == "text/html" {
        // Cheap HTML strip — drop tags. Good enough for digest.
        let html = part.get_body().ok()?;
        return Some(strip_html(&html));
    }
    for sub in &part.subparts {
        if let Some(body) = first_text_body(sub) {
            return Some(body);
        }
    }
    None
}

fn strip_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut in_tag = false;
    for c in s.chars() {
        match c {
            '<' => in_tag = true,
            '>' => in_tag = false,
            _ if !in_tag => out.push(c),
            _ => {}
        }
    }
    out.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Group a flat list of messages into threads by normalised subject. We
/// also unify threads via the `references` chain — if message B has a
/// reference to message A's Message-ID, B joins A's group regardless of
/// subject (handles the "subject changed mid-thread" case).
pub fn thread_messages(messages: Vec<EmailMessage>) -> Vec<EmailThread> {
    let mut by_subject: BTreeMap<String, EmailThread> = BTreeMap::new();
    let mut id_to_subject: BTreeMap<String, String> = BTreeMap::new();
    // First pass — group by subject root.
    for m in &messages {
        let root = normalise_subject(&m.subject);
        if !m.message_id.is_empty() {
            id_to_subject.insert(m.message_id.clone(), root.clone());
        }
        let entry = by_subject
            .entry(root.clone())
            .or_insert_with(|| EmailThread {
                subject_root: root.clone(),
                messages: Vec::new(),
            });
        entry.messages.push(m.clone());
    }
    // Second pass — for each message, if any of its `references` points
    // at a Message-ID in a different subject group, merge the smaller
    // group into the larger one.
    let mut merge_into: BTreeMap<String, String> = BTreeMap::new();
    for m in &messages {
        let own_root = normalise_subject(&m.subject);
        for r in &m.references {
            if let Some(other_root) = id_to_subject.get(r) {
                if other_root != &own_root {
                    let (winner, loser) = if other_root < &own_root {
                        (other_root.clone(), own_root.clone())
                    } else {
                        (own_root.clone(), other_root.clone())
                    };
                    merge_into.insert(loser, winner);
                }
            }
        }
    }
    // Resolve transitive merges (loser → winner → ...).
    let mut resolved: BTreeMap<String, String> = BTreeMap::new();
    for (loser, _) in merge_into.iter() {
        let mut cur = loser.clone();
        let mut seen = BTreeSet::new();
        while let Some(next) = merge_into.get(&cur) {
            if !seen.insert(cur.clone()) {
                break;
            }
            cur = next.clone();
        }
        resolved.insert(loser.clone(), cur);
    }
    for (loser, winner) in resolved {
        if let Some(thread) = by_subject.remove(&loser) {
            if let Some(target) = by_subject.get_mut(&winner) {
                target.messages.extend(thread.messages);
            } else {
                // Winner gone — keep the loser group intact under its own key.
                by_subject.insert(loser, thread);
            }
        }
    }
    // Sort messages inside each thread by date (best-effort string compare;
    // RFC 3339 sorts lexicographically when timezone-normalised, which our
    // parser ensures).
    let mut threads: Vec<EmailThread> = by_subject.into_values().collect();
    for t in &mut threads {
        t.messages.sort_by(|a, b| a.date.cmp(&b.date));
    }
    threads
}

// ---------------------------------------------------------------------------
// Filesystem layer

/// `<memory_root>/threads/email/`. Created on demand.
pub fn email_threads_dir(memory_root: &Path) -> PathBuf {
    memory_root.join("threads").join("email")
}

/// Resolve the default memory root: `<home>/.tangerine-memory/`.
fn default_memory_root() -> Result<PathBuf, AppError> {
    dirs::home_dir()
        .map(|h| h.join(".tangerine-memory"))
        .ok_or_else(|| AppError::internal("home_dir", "home_dir() returned None"))
}

/// Write (or merge) thread atoms into the email threads dir. Returns the
/// number of atoms written or merged.
pub fn write_threads(
    memory_root: &Path,
    threads: &[EmailThread],
    provider: &str,
) -> Result<u32, AppError> {
    let dir = email_threads_dir(memory_root);
    std::fs::create_dir_all(&dir)
        .map_err(|e| AppError::internal("mkdir_email", e.to_string()))?;
    let mut written = 0u32;
    for t in threads {
        if t.messages.is_empty() {
            continue;
        }
        let slug = t.slug();
        let path = dir.join(format!("{}.md", slug));
        let existing_ids = read_existing_message_ids(&path);
        // Merge: drop messages whose IDs are already on disk.
        let mut merged = EmailThread {
            subject_root: t.subject_root.clone(),
            messages: Vec::new(),
        };
        for m in &t.messages {
            if !m.message_id.is_empty() && existing_ids.contains(&m.message_id) {
                continue;
            }
            merged.messages.push(m.clone());
        }
        if merged.messages.is_empty() {
            continue;
        }
        // If we have prior content, splice the existing messages back in by
        // re-reading their IDs from disk and treating them as already
        // present in the body; the simpler approach (rewriting from scratch
        // with both old + new) requires re-fetching old bodies which we no
        // longer have. Instead we append a "merged on" marker — the
        // frontmatter `message_ids` reflects the union so future fetches
        // dedup correctly.
        if !existing_ids.is_empty() {
            // Pseudo-thread carrying existing IDs as ghost entries — keeps
            // the message_ids: list complete in frontmatter.
            for id in &existing_ids {
                merged.messages.insert(
                    0,
                    EmailMessage {
                        message_id: id.clone(),
                        subject: String::new(),
                        from: String::new(),
                        to: vec![],
                        cc: vec![],
                        date: String::new(),
                        body: String::from("(previously recorded message — body archived)"),
                        references: vec![],
                    },
                );
            }
        }
        let body = build_email_atom(&merged, provider);
        atomic_write(&path, &body)?;
        written += 1;
    }
    Ok(written)
}

/// Atomic write: tmp file + rename. Mirrors the helper in
/// `commands::views::atomic_write`.
fn atomic_write(path: &Path, body: &str) -> Result<(), AppError> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).ok();
    }
    let tmp = path.with_extension(format!("tmp.{}", uuid::Uuid::new_v4().simple()));
    std::fs::write(&tmp, body)
        .map_err(|e| AppError::internal("atomic_write_email", format!("write: {e}")))?;
    std::fs::rename(&tmp, path)
        .map_err(|e| AppError::internal("atomic_write_email", format!("rename: {e}")))?;
    Ok(())
}

// ---------------------------------------------------------------------------
// IMAP transport — production. Hidden behind `cfg(not(test))` no-op stubs to
// keep the test surface deterministic; the real wiring uses `imap::Client`.

#[cfg(not(test))]
fn connect_imap_blocking(
    host: &str,
    port: u16,
    username: &str,
    password: &str,
) -> Result<imap::Session<imap::Connection>, String> {
    let client = imap::ClientBuilder::new(host, port)
        .connect()
        .map_err(|e| format!("connect: {e}"))?;
    let session = client
        .login(username, password)
        .map_err(|(e, _)| format!("login: {e}"))?;
    Ok(session)
}

#[cfg(not(test))]
fn fetch_recent_via_imap(
    cfg: &EmailConfig,
    password: &str,
    since: DateTime<Utc>,
) -> Result<Vec<(u32, Vec<u8>)>, String> {
    let (host, port) = cfg.imap_endpoint().map_err(|e| e.to_string())?;
    let mut session = connect_imap_blocking(&host, port, &cfg.username, password)?;
    session
        .select("INBOX")
        .map_err(|e| format!("select inbox: {e}"))?;
    // IMAP SINCE date format: `DD-Mon-YYYY` per RFC 3501.
    let since_str = since.format("%d-%b-%Y").to_string();
    let uids = session
        .uid_search(format!("SINCE {}", since_str))
        .map_err(|e| format!("search: {e}"))?;
    if uids.is_empty() {
        let _ = session.logout();
        return Ok(vec![]);
    }
    let uid_set = uids
        .iter()
        .map(|u| u.to_string())
        .collect::<Vec<_>>()
        .join(",");
    let messages = session
        .uid_fetch(&uid_set, "RFC822")
        .map_err(|e| format!("fetch: {e}"))?;
    let mut out = Vec::new();
    for msg in messages.iter() {
        if let (Some(uid), Some(body)) = (msg.uid, msg.body()) {
            out.push((uid, body.to_vec()));
        }
    }
    let _ = session.logout();
    Ok(out)
}

// ---------------------------------------------------------------------------
// Public entry — used by the daemon heartbeat hook + the manual fetch button.

#[derive(Debug, Clone, Serialize)]
pub struct FetchResult {
    pub threads_written: u32,
    pub messages_seen: u32,
    pub provider: String,
}

/// Fetch recent messages, group, and write atoms. Reads the password from
/// `TokenStore` keyed on `cfg.keyring_login()`. Memory root defaults to
/// `<home>/.tangerine-memory/` unless `memory_root_override` is given.
pub async fn fetch_recent(
    cfg: EmailConfig,
    memory_root_override: Option<PathBuf>,
) -> Result<FetchResult, AppError> {
    if cfg.fetch_lookback_days == 0 || cfg.fetch_lookback_days > 30 {
        return Err(AppError::user(
            "lookback_oob",
            "fetch_lookback_days must be in 1..=30",
        ));
    }
    let memory_root = match memory_root_override {
        Some(p) => p,
        None => default_memory_root()?,
    };
    let password = TokenStore::get(&cfg.keyring_login()).map_err(|_| {
        AppError::user(
            "email_password_missing",
            "no app password stored — run /sources/email setup first",
        )
    })?;
    let since = Utc::now() - chrono::Duration::days(cfg.fetch_lookback_days as i64);

    let raw = fetch_via_blocking(&cfg, &password, since).await?;
    let messages_seen = raw.len() as u32;
    let mut messages: Vec<EmailMessage> = Vec::new();
    for (_uid, body) in raw {
        match parse_rfc822(&body) {
            Ok(m) => messages.push(m),
            Err(e) => tracing::warn!(error = %e, "email: parse_rfc822 failed; skipping message"),
        }
    }
    let threads = thread_messages(messages);
    let written = write_threads(&memory_root, &threads, &cfg.provider)?;
    Ok(FetchResult {
        threads_written: written,
        messages_seen,
        provider: cfg.provider,
    })
}

#[cfg(not(test))]
async fn fetch_via_blocking(
    cfg: &EmailConfig,
    password: &str,
    since: DateTime<Utc>,
) -> Result<Vec<(u32, Vec<u8>)>, AppError> {
    let cfg = cfg.clone();
    let password = password.to_string();
    let join = tokio::task::spawn_blocking(move || fetch_recent_via_imap(&cfg, &password, since))
        .await
        .map_err(|e| AppError::internal("imap_join", e.to_string()))?;
    join.map_err(|e| AppError::external("imap", e))
}

#[cfg(test)]
async fn fetch_via_blocking(
    _cfg: &EmailConfig,
    _password: &str,
    _since: DateTime<Utc>,
) -> Result<Vec<(u32, Vec<u8>)>, AppError> {
    // Tests inject messages directly through `write_threads` / `parse_rfc822`,
    // not through this layer — so just return empty so the code path stays
    // exercised.
    Ok(vec![])
}

// ---------------------------------------------------------------------------
// Tauri commands — invoked from the React layer.

#[derive(Debug, Deserialize)]
pub struct EmailTestConnectionArgs {
    pub config: EmailConfig,
}

#[derive(Debug, Serialize)]
pub struct EmailTestConnectionResult {
    pub ok: bool,
    pub host: String,
    pub port: u16,
    pub error: Option<String>,
    /// True when the password got stored. False on dry-run (no password).
    pub stored_password: bool,
}

/// Tests the IMAP login. On success, persists the app password to the
/// keychain so subsequent fetches use the stored credential.
#[tauri::command(rename_all = "snake_case")]
pub async fn email_test_connection(
    _state: State<'_, AppState>,
    args: EmailTestConnectionArgs,
) -> Result<EmailTestConnectionResult, AppError> {
    let cfg = args.config;
    if cfg.username.trim().is_empty() {
        return Ok(EmailTestConnectionResult {
            ok: false,
            host: String::new(),
            port: 0,
            error: Some("username is empty".into()),
            stored_password: false,
        });
    }
    let (host, port) = cfg.imap_endpoint()?;
    let password = match cfg.app_password.as_deref() {
        Some(p) if !p.is_empty() => p.to_string(),
        _ => {
            return Ok(EmailTestConnectionResult {
                ok: false,
                host,
                port,
                error: Some("app password is empty".into()),
                stored_password: false,
            });
        }
    };
    // Try a real login. Wrapped in spawn_blocking to keep the runtime free.
    #[cfg(not(test))]
    {
        let host_c = host.clone();
        let user = cfg.username.clone();
        let pwd = password.clone();
        let join = tokio::task::spawn_blocking(move || {
            connect_imap_blocking(&host_c, port, &user, &pwd).map(|mut s| {
                let _ = s.logout();
            })
        })
        .await
        .map_err(|e| AppError::internal("imap_join", e.to_string()))?;
        if let Err(e) = join {
            return Ok(EmailTestConnectionResult {
                ok: false,
                host,
                port,
                error: Some(e),
                stored_password: false,
            });
        }
    }
    // Persist the password on success.
    TokenStore::set(&cfg.keyring_login(), &password)?;
    Ok(EmailTestConnectionResult {
        ok: true,
        host,
        port,
        error: None,
        stored_password: true,
    })
}

#[derive(Debug, Deserialize)]
pub struct EmailFetchRecentArgs {
    pub config: EmailConfig,
}

#[tauri::command(rename_all = "snake_case")]
pub async fn email_fetch_recent(
    _state: State<'_, AppState>,
    args: EmailFetchRecentArgs,
) -> Result<FetchResult, AppError> {
    fetch_recent(args.config, None).await
}

// ---------------------------------------------------------------------------
// Tests

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_message(id: &str, subj: &str, from: &str, date: &str) -> EmailMessage {
        EmailMessage {
            message_id: id.to_string(),
            subject: subj.to_string(),
            from: from.to_string(),
            to: vec!["bob@example.com".to_string()],
            cc: vec![],
            date: date.to_string(),
            body: format!("hello from {}", from),
            references: vec![],
        }
    }

    #[test]
    fn imap_endpoint_resolves_known_providers() {
        let g = EmailConfig {
            provider: "gmail".into(),
            username: "x@gmail.com".into(),
            app_password: None,
            fetch_lookback_days: 7,
            host: None,
            port: None,
        };
        assert_eq!(g.imap_endpoint().unwrap(), ("imap.gmail.com".into(), 993));
        let o = EmailConfig {
            provider: "outlook".into(),
            ..g.clone()
        };
        assert_eq!(
            o.imap_endpoint().unwrap(),
            ("outlook.office365.com".into(), 993)
        );
    }

    #[test]
    fn imap_endpoint_rejects_unknown_provider() {
        let cfg = EmailConfig {
            provider: "yahoo-fast-mail-mash".into(),
            username: "x".into(),
            app_password: None,
            fetch_lookback_days: 7,
            host: None,
            port: None,
        };
        assert!(cfg.imap_endpoint().is_err());
    }

    #[test]
    fn imap_endpoint_honours_explicit_override() {
        let cfg = EmailConfig {
            provider: "imap".into(),
            username: "x".into(),
            app_password: None,
            fetch_lookback_days: 7,
            host: Some("mail.fastmail.com".into()),
            port: Some(993),
        };
        assert_eq!(
            cfg.imap_endpoint().unwrap(),
            ("mail.fastmail.com".into(), 993)
        );
    }

    #[test]
    fn normalise_subject_strips_re_fwd_and_brackets() {
        assert_eq!(normalise_subject("Re: [Eng] OKRs"), "okrs");
        assert_eq!(normalise_subject("Fwd: Re: meeting"), "meeting");
        assert_eq!(normalise_subject("回复: 项目计划"), "项目计划");
        assert_eq!(normalise_subject("plain subject"), "plain subject");
    }

    #[test]
    fn slugify_subject_trims_to_40() {
        let s = slugify_subject(&"a".repeat(100));
        assert!(s.chars().count() <= 40);
        assert_eq!(slugify_subject(""), "untitled");
        // Real-world: "Re: Eng/Q2 sync — let's chat" after normalisation.
        let real = slugify_subject("Eng/Q2 sync — let's chat");
        assert!(real.contains("eng"));
        assert!(real.contains("sync"));
    }

    #[test]
    fn test_email_atom_format() {
        // Locked frontmatter shape — the daemon and React reader both rely
        // on these exact key names.
        let t = EmailThread {
            subject_root: "okrs".into(),
            messages: vec![
                fixture_message(
                    "msg1@example.com",
                    "Re: OKRs",
                    "alice@example.com",
                    "2026-04-26T10:00:00+00:00",
                ),
                fixture_message(
                    "msg2@example.com",
                    "Re: OKRs",
                    "bob@example.com",
                    "2026-04-26T11:00:00+00:00",
                ),
            ],
        };
        let body = build_email_atom(&t, "gmail");
        assert!(body.starts_with("---\n"));
        assert!(body.contains("source: email\n"));
        assert!(body.contains("provider: gmail\n"));
        assert!(body.contains("subject: "));
        assert!(body.contains("participants:\n"));
        assert!(body.contains("  - alice@example.com\n"));
        assert!(body.contains("  - bob@example.com\n"));
        assert!(body.contains("last_message_at: "));
        assert!(body.contains("message_ids:\n"));
        assert!(body.contains("  - msg1@example.com\n"));
        assert!(body.contains("  - msg2@example.com\n"));
        // Body section
        assert!(body.contains("# Re: OKRs"));
        assert!(body.contains("## alice@example.com — 2026-04-26T10:00:00+00:00"));
    }

    #[test]
    fn thread_messages_groups_by_subject_root() {
        let m1 = fixture_message("a@x", "Project X", "a@x", "2026-04-26T10:00:00+00:00");
        let m2 = fixture_message("b@x", "Re: Project X", "b@x", "2026-04-26T11:00:00+00:00");
        let m3 = fixture_message("c@x", "different topic", "c@x", "2026-04-26T12:00:00+00:00");
        let threads = thread_messages(vec![m1, m2, m3]);
        assert_eq!(threads.len(), 2);
        let proj = threads
            .iter()
            .find(|t| t.subject_root == "project x")
            .unwrap();
        assert_eq!(proj.messages.len(), 2);
    }

    #[test]
    fn thread_messages_chains_via_references() {
        // Subject changed mid-thread — but the second message references
        // the first. They should still group together.
        let m1 = fixture_message("a@x", "Original", "a@x", "2026-04-26T10:00:00+00:00");
        let mut m2 = fixture_message(
            "b@x",
            "Branched off — new topic",
            "b@x",
            "2026-04-26T11:00:00+00:00",
        );
        m2.references = vec!["a@x".to_string()];
        let threads = thread_messages(vec![m1, m2]);
        // After merge resolution we expect ONE thread holding both messages.
        let combined: Vec<_> = threads.iter().filter(|t| t.messages.len() == 2).collect();
        assert_eq!(combined.len(), 1, "got {:?}", threads);
    }

    #[test]
    fn test_email_thread_dedup() {
        // Fetching the same set of messages twice should leave the atom
        // file unchanged in spirit (no duplicate message_ids / sections).
        let tmp = std::env::temp_dir().join(format!(
            "tmi_email_dedup_{}",
            uuid::Uuid::new_v4().simple()
        ));
        std::fs::create_dir_all(&tmp).unwrap();
        let m = fixture_message(
            "msg-dedup@example.com",
            "Project plan",
            "alice@example.com",
            "2026-04-26T10:00:00+00:00",
        );
        let t = EmailThread {
            subject_root: normalise_subject(&m.subject),
            messages: vec![m.clone()],
        };
        // First write.
        let n1 = write_threads(&tmp, &[t.clone()], "gmail").unwrap();
        assert_eq!(n1, 1);
        let path = email_threads_dir(&tmp).join(format!("{}.md", t.slug()));
        let first_body = std::fs::read_to_string(&path).unwrap();
        // Second write with the SAME message — should be a no-op (no new
        // message remains after dedup).
        let n2 = write_threads(&tmp, &[t.clone()], "gmail").unwrap();
        assert_eq!(n2, 0, "second write should be a no-op");
        let second_body = std::fs::read_to_string(&path).unwrap();
        assert_eq!(first_body, second_body);
        // The on-disk file lists the message ID exactly once.
        let count = first_body
            .matches("- msg-dedup@example.com\n")
            .count();
        assert_eq!(count, 1);
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn test_email_thread_dedup_preserves_existing_ids() {
        // Even when the SECOND fetch contains an entirely new message, the
        // existing message_id stays in the frontmatter.
        let tmp = std::env::temp_dir().join(format!(
            "tmi_email_dedup2_{}",
            uuid::Uuid::new_v4().simple()
        ));
        std::fs::create_dir_all(&tmp).unwrap();
        let m1 = fixture_message(
            "first@x",
            "Plan",
            "alice@example.com",
            "2026-04-26T10:00:00+00:00",
        );
        let t1 = EmailThread {
            subject_root: normalise_subject(&m1.subject),
            messages: vec![m1.clone()],
        };
        write_threads(&tmp, &[t1], "gmail").unwrap();

        let m2 = fixture_message(
            "second@x",
            "Re: Plan",
            "bob@example.com",
            "2026-04-26T11:00:00+00:00",
        );
        let t2 = EmailThread {
            subject_root: normalise_subject(&m2.subject),
            messages: vec![m2.clone()],
        };
        write_threads(&tmp, &[t2], "gmail").unwrap();

        let path = email_threads_dir(&tmp).join("plan.md");
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("- first@x"), "lost old id: {}", body);
        assert!(body.contains("- second@x"));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn read_existing_message_ids_pulls_from_frontmatter() {
        let tmp = std::env::temp_dir().join(format!(
            "tmi_email_read_ids_{}",
            uuid::Uuid::new_v4().simple()
        ));
        std::fs::create_dir_all(&tmp).unwrap();
        let path = tmp.join("foo.md");
        std::fs::write(
            &path,
            "---\n\
source: email\n\
subject: x\n\
message_ids:\n  - a@x\n  - b@x\n  - c@x\nlast_message_at: 2026-04-26\n---\n\nbody\n",
        )
        .unwrap();
        let ids = read_existing_message_ids(&path);
        assert_eq!(ids.len(), 3);
        assert!(ids.contains("a@x"));
        assert!(ids.contains("c@x"));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn parse_rfc822_smoke() {
        let raw = b"From: alice@example.com\r\n\
To: bob@example.com\r\n\
Subject: Hello\r\n\
Message-ID: <abc@x>\r\n\
Date: Sun, 26 Apr 2026 10:00:00 +0000\r\n\
\r\n\
hi from alice\r\n";
        let m = parse_rfc822(raw).unwrap();
        assert_eq!(m.message_id, "abc@x");
        assert_eq!(m.subject, "Hello");
        assert!(m.from.contains("alice@example.com"));
        assert!(m.body.contains("hi from alice"));
    }

    #[test]
    fn parse_rfc822_handles_missing_date() {
        let raw = b"From: a\r\nSubject: x\r\nMessage-ID: <q@x>\r\n\r\nbody\r\n";
        let m = parse_rfc822(raw).unwrap();
        // Falls back to "now" — just check the result is RFC 3339-shaped.
        assert!(m.date.contains('T'));
    }

    #[test]
    fn yaml_scalar_quotes_when_needed() {
        assert_eq!(yaml_scalar("plain"), "plain");
        assert_eq!(yaml_scalar("a: b"), "\"a: b\"");
        assert_eq!(yaml_scalar(""), "\"\"");
        assert_eq!(yaml_scalar("- foo"), "\"- foo\"");
    }

    #[test]
    fn fetch_recent_rejects_zero_or_huge_lookback() {
        // We'd test via a runtime, but the public `fetch_recent` is async —
        // instead invoke the validation guard via a dummy executor.
        let rt = tokio::runtime::Runtime::new().unwrap();
        let cfg_zero = EmailConfig {
            provider: "gmail".into(),
            username: "x@x".into(),
            app_password: Some("p".into()),
            fetch_lookback_days: 0,
            host: None,
            port: None,
        };
        assert!(rt.block_on(fetch_recent(cfg_zero, None)).is_err());
        let cfg_big = EmailConfig {
            provider: "gmail".into(),
            username: "x@x".into(),
            app_password: Some("p".into()),
            fetch_lookback_days: 365,
            host: None,
            port: None,
        };
        assert!(rt.block_on(fetch_recent(cfg_big, None)).is_err());
    }
}
