//! v1.17.1 — TEAM_INDEX.md auto-write.
//!
//! Solves the AI-AI alignment pain Daizhe surfaced this session: a fresh
//! AI session not knowing what an earlier session built. We bridge atoms
//! → AI sessions by emitting a compact (~5 KB target, 10 KB hard ceiling)
//! Markdown summary of recent team activity at
//! `<memory_root>/TEAM_INDEX.md`. Any AI tool that reads the user's
//! project `CLAUDE.md` or Cursor rules can `@import` the file and pick up
//! the team's recent working memory without bespoke wiring.
//!
//! File ownership rule: only Tangerine writes TEAM_INDEX.md. The first
//! line of the file is the canonical Tangerine sentinel so a careful
//! human edit never silently survives a rewrite.
//!
//! Trigger surface:
//!   * `write_team_index` Tauri command (manual / setup wizard).
//!   * Daemon heartbeat — `do_heartbeat` calls `write_team_index_to`
//!     after `index-rebuild` so every successful ingestion refreshes the
//!     bridge file. The cadence inherits the daemon's existing 5 min
//!     foreground / 30 min background tick.
//!
//! Honesty: when the memory dir is empty (zero atoms), we still write a
//! header-only stub explaining "no atoms captured yet" rather than
//! failing silently. R6/R7 rule — no fake activity.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use chrono::{DateTime, Duration, Utc};
use serde::Serialize;

use super::views::{atomic_write, load_all_events, memory_root, TimelineEvent};
use super::AppError;

/// Sentinel inserted as the first line of every emitted TEAM_INDEX.md.
/// Surfaced to humans + greppable from CI; if a contributor opens the
/// file and sees this line they know hand-edits will be overwritten.
const SENTINEL: &str =
    "<!-- Auto-generated by Tangerine AI Teams. Manual edits will be overwritten. -->";

/// Hard ceiling for the on-disk TEAM_INDEX.md. We aim for ~5 KB; if the
/// composer overshoots we truncate the "Recent atoms" section first.
/// 10 240 bytes is the load-bearing economics number — context windows
/// are precious and a runaway file would burn budget on every AI turn.
const HARD_CEILING_BYTES: usize = 10_240;

/// Default ceilings for each list section. The composer trims further
/// only when the rendered total still busts `HARD_CEILING_BYTES`.
const MAX_DECISIONS: usize = 10;
const MAX_THREADS: usize = 10;
const MAX_PEOPLE: usize = 8;
const MAX_RECENT_ATOMS: usize = 30;

/// Per-list time windows. Decisions + threads look back 7 days; people +
/// recent-atoms look back 24 h.
const DECISIONS_WINDOW_DAYS: i64 = 7;
const THREADS_WINDOW_DAYS: i64 = 7;
const PEOPLE_WINDOW_HOURS: i64 = 24;
const RECENT_ATOMS_WINDOW_HOURS: i64 = 24;

#[derive(Debug, Serialize)]
pub struct TeamIndexOut {
    /// Absolute path to the file we just wrote.
    pub path: String,
    /// Total events scanned out of `timeline.json`.
    pub atoms_scanned: u32,
    /// On-disk byte size of the file we wrote.
    pub bytes_written: u64,
}

/// Tauri command — resolve memory root, build the body, atomic-write to
/// `<root>/TEAM_INDEX.md`. Returns the resolved path + counters.
#[tauri::command]
pub async fn write_team_index() -> Result<TeamIndexOut, AppError> {
    let root = memory_root()?;
    write_team_index_to(&root)
}

/// Driver — same as the Tauri command but scoped to an explicit root so
/// the daemon (which already owns `cfg.memory_root`) and unit tests can
/// reuse it without rebuilding the resolution chain.
pub fn write_team_index_to(root: &Path) -> Result<TeamIndexOut, AppError> {
    std::fs::create_dir_all(root).map_err(|e| {
        AppError::internal("team_index_mkdir", format!("create_dir_all {root:?}: {e}"))
    })?;
    let events = load_all_events(root);
    let atoms_scanned = events.len() as u32;
    let now = Utc::now();
    let body = build_team_index_markdown(&events, now);
    let path = team_index_path(root);
    atomic_write(&path, &body)?;
    let bytes_written = std::fs::metadata(&path)
        .map(|m| m.len())
        .unwrap_or(body.len() as u64);
    Ok(TeamIndexOut {
        path: path.to_string_lossy().into_owned(),
        atoms_scanned,
        bytes_written,
    })
}

fn team_index_path(root: &Path) -> PathBuf {
    root.join("TEAM_INDEX.md")
}

// --------------------------------------------------------------------------
// Markdown composer — pure function over events + clock for testability.

/// Build the TEAM_INDEX.md body. Pure — `events` + `now` are the only
/// inputs. Visible to siblings via `pub(crate)` so the daemon can
/// pre-compose without touching disk in tests.
pub(crate) fn build_team_index_markdown(events: &[TimelineEvent], now: DateTime<Utc>) -> String {
    if events.iter().all(|e| e.sample) || events.is_empty() {
        return empty_stub(now);
    }
    let sane: Vec<&TimelineEvent> = events.iter().filter(|e| !e.sample).collect();
    let recent_decisions = section_recent_decisions(&sane, now, MAX_DECISIONS);
    let active_threads = section_active_threads(&sane, now, MAX_THREADS);
    let active_people = section_active_people(&sane, now, MAX_PEOPLE);
    let mut recent_atoms = section_recent_atoms(&sane, now, MAX_RECENT_ATOMS);

    let mut body = compose(
        now,
        sane.len() as u32,
        &recent_decisions,
        &active_threads,
        &active_people,
        &recent_atoms,
    );
    if body.len() <= HARD_CEILING_BYTES {
        return body;
    }
    // Over budget — trim "Recent atoms" first (the most truncatable
    // section). Halve repeatedly until we fit or run out of rows.
    let mut budget = recent_atoms.len();
    while body.len() > HARD_CEILING_BYTES && budget > 0 {
        budget = budget.saturating_sub((budget / 2).max(1));
        recent_atoms.truncate(budget);
        body = compose(
            now,
            sane.len() as u32,
            &recent_decisions,
            &active_threads,
            &active_people,
            &recent_atoms,
        );
    }
    if body.len() > HARD_CEILING_BYTES {
        // Still over — drop the section entirely. Header + the three
        // top sections are load-bearing; recent atoms can be looked up
        // in the per-day timeline files.
        body = compose(
            now,
            sane.len() as u32,
            &recent_decisions,
            &active_threads,
            &active_people,
            &[],
        );
    }
    body
}

fn compose(
    now: DateTime<Utc>,
    atoms_scanned: u32,
    decisions: &[String],
    threads: &[String],
    people: &[String],
    recent_atoms: &[String],
) -> String {
    let mut out = String::with_capacity(4096);
    out.push_str(SENTINEL);
    out.push('\n');
    out.push_str("# Tangerine Team Memory — auto-generated by Tangerine AI Teams v1.17.1\n");
    out.push_str(&format!(
        "Last updated: {} · {} atoms scanned\n",
        now.to_rfc3339(),
        atoms_scanned
    ));
    out.push_str("\n## Recent decisions (last 7 days, top 10)\n");
    if decisions.is_empty() {
        out.push_str("- (no decision atoms in the last 7 days)\n");
    } else {
        for line in decisions {
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str("\n## Active threads (last 7 days, top 10)\n");
    if threads.is_empty() {
        out.push_str("- (no thread activity in the last 7 days)\n");
    } else {
        for line in threads {
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str("\n## Who's been active (last 24h)\n");
    if people.is_empty() {
        out.push_str("- (no actor activity in the last 24h)\n");
    } else {
        for line in people {
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str("\n## Recent atoms (last 24h, top 30)\n");
    if recent_atoms.is_empty() {
        out.push_str("- (no atoms in the last 24h)\n");
    } else {
        for line in recent_atoms {
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str("\n---\n\n");
    out.push_str(
        "If you're an AI session reading this: this is your team's recent\n\
         working memory. Cite atom IDs when you reference them. Full atom\n\
         history is at ~/.tangerine-memory/personal/<alias>/threads/.\n",
    );
    out
}

fn empty_stub(now: DateTime<Utc>) -> String {
    let mut out = String::new();
    out.push_str(SENTINEL);
    out.push('\n');
    out.push_str("# Tangerine Team Memory — auto-generated by Tangerine AI Teams v1.17.1\n");
    out.push_str(&format!(
        "Last updated: {} · 0 atoms scanned\n",
        now.to_rfc3339()
    ));
    out.push_str(
        "\nNo atoms captured yet. Once Tangerine ingests your first AI\n\
         session, this file will list recent decisions, active threads,\n\
         who's working, and the latest atoms.\n",
    );
    out.push_str("\n---\n\n");
    out.push_str(
        "If you're an AI session reading this: the user's team has not\n\
         captured any AI sessions yet. Continue normally; future sessions\n\
         will see your work once Tangerine is wired into one of their AI\n\
         tools (Cursor, Claude Code, Codex, Windsurf, ...).\n",
    );
    out
}

// --------------------------------------------------------------------------
// Section builders. Each takes the cleaned event slice + clock + cap and
// returns a `Vec<String>` of pre-rendered Markdown bullet lines.

fn section_recent_decisions(
    events: &[&TimelineEvent],
    now: DateTime<Utc>,
    cap: usize,
) -> Vec<String> {
    let cutoff = now - Duration::days(DECISIONS_WINDOW_DAYS);
    let mut decisions: Vec<&TimelineEvent> = events
        .iter()
        .copied()
        .filter(|e| {
            event_within(e, cutoff)
                && (e.kind.eq_ignore_ascii_case("decision")
                    || e.kind.eq_ignore_ascii_case("decision_atom"))
        })
        .collect();
    decisions.sort_by(|a, b| b.ts.cmp(&a.ts));
    decisions
        .into_iter()
        .take(cap)
        .map(|e| {
            let date = e.ts.get(..10).unwrap_or(&e.ts);
            let tag = primary_tag(e);
            let actor = if e.actor.is_empty() { "?" } else { &e.actor };
            let body = first_line_trunc(e.body.as_deref().unwrap_or(""), 80);
            format!("- {date} [{tag}] {actor} — {body}")
        })
        .collect()
}

fn section_active_threads(
    events: &[&TimelineEvent],
    now: DateTime<Utc>,
    cap: usize,
) -> Vec<String> {
    let cutoff = now - Duration::days(THREADS_WINDOW_DAYS);
    // Group by topic. Collect: members (BTreeSet of actor aliases),
    // count, last ts, last body.
    let mut by_topic: BTreeMap<String, ThreadAgg> = BTreeMap::new();
    for ev in events {
        if !event_within(ev, cutoff) {
            continue;
        }
        for topic in event_threads(ev) {
            let entry = by_topic.entry(topic).or_default();
            entry.count += 1;
            for a in event_actors(ev) {
                entry.members.insert(a);
            }
            if entry.last_ts.as_deref().is_none_or(|cur| ev.ts.as_str() > cur) {
                entry.last_ts = Some(ev.ts.clone());
                entry.last_body = ev.body.clone().unwrap_or_default();
            }
        }
    }
    let mut rows: Vec<(String, ThreadAgg)> = by_topic.into_iter().collect();
    rows.sort_by(|(_, a), (_, b)| b.last_ts.cmp(&a.last_ts));
    rows.into_iter()
        .take(cap)
        .map(|(_topic, agg)| {
            let mentions = agg
                .members
                .iter()
                .take(4)
                .map(|m| format!("@{m}"))
                .collect::<Vec<_>>()
                .join(" ");
            let last_seen = relative_ago(agg.last_ts.as_deref(), now);
            let body = first_line_trunc(&agg.last_body, 60);
            format!(
                "- {mentions} · {} atoms · last {last_seen} · \"{body}\"",
                agg.count
            )
        })
        .collect()
}

#[derive(Default)]
struct ThreadAgg {
    count: u32,
    members: std::collections::BTreeSet<String>,
    last_ts: Option<String>,
    last_body: String,
}

fn section_active_people(
    events: &[&TimelineEvent],
    now: DateTime<Utc>,
    cap: usize,
) -> Vec<String> {
    let cutoff = now - Duration::hours(PEOPLE_WINDOW_HOURS);
    let mut by_alias: BTreeMap<String, PersonAgg> = BTreeMap::new();
    for ev in events {
        if !event_within(ev, cutoff) {
            continue;
        }
        for actor in event_actors(ev) {
            let entry = by_alias.entry(actor).or_default();
            entry.count += 1;
            if !ev.source.is_empty() {
                entry.sources.insert(ev.source.clone());
            }
            for tag in event_tags(ev) {
                *entry.tag_counts.entry(tag).or_insert(0) += 1u32;
            }
        }
    }
    let mut rows: Vec<(String, PersonAgg)> = by_alias.into_iter().collect();
    rows.sort_by(|(_, a), (_, b)| b.count.cmp(&a.count));
    rows.into_iter()
        .take(cap)
        .map(|(alias, agg)| {
            let sources = agg
                .sources
                .iter()
                .take(3)
                .cloned()
                .collect::<Vec<_>>()
                .join(", ");
            let mut tags: Vec<(String, u32)> = agg.tag_counts.into_iter().collect();
            tags.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(&b.0)));
            let top_tags = tags
                .into_iter()
                .take(3)
                .map(|(t, _)| t)
                .collect::<Vec<_>>()
                .join(", ");
            let tag_part = if top_tags.is_empty() {
                String::new()
            } else {
                format!(" · top tags: {top_tags}")
            };
            format!(
                "- {alias} · {sources} · {} atoms{tag_part}",
                agg.count
            )
        })
        .collect()
}

#[derive(Default)]
struct PersonAgg {
    count: u32,
    sources: std::collections::BTreeSet<String>,
    tag_counts: BTreeMap<String, u32>,
}

fn section_recent_atoms(
    events: &[&TimelineEvent],
    now: DateTime<Utc>,
    cap: usize,
) -> Vec<String> {
    let cutoff = now - Duration::hours(RECENT_ATOMS_WINDOW_HOURS);
    let mut recent: Vec<&TimelineEvent> = events
        .iter()
        .copied()
        .filter(|e| event_within(e, cutoff))
        .collect();
    recent.sort_by(|a, b| b.ts.cmp(&a.ts));
    recent
        .into_iter()
        .take(cap)
        .map(|e| {
            let hhmm = e.ts.get(11..16).unwrap_or("?");
            let actor = if e.actor.is_empty() { "?" } else { &e.actor };
            let source = if e.source.is_empty() {
                "?"
            } else {
                e.source.as_str()
            };
            let body = first_line_trunc(e.body.as_deref().unwrap_or(""), 80);
            format!("- {hhmm} {actor} [{source}] — {body}")
        })
        .collect()
}

// --------------------------------------------------------------------------
// Tiny utilities — text trim, time math, ref decode.

fn first_line_trunc(body: &str, max: usize) -> String {
    let line = body.lines().next().unwrap_or("").trim();
    if line.is_empty() {
        return "(no body)".to_string();
    }
    if line.chars().count() <= max {
        return line.to_string();
    }
    let mut out = String::with_capacity(max + 1);
    for (i, ch) in line.chars().enumerate() {
        if i >= max.saturating_sub(1) {
            break;
        }
        out.push(ch);
    }
    out.push('…');
    out
}

fn event_within(e: &TimelineEvent, cutoff: DateTime<Utc>) -> bool {
    let Ok(parsed) = DateTime::parse_from_rfc3339(&e.ts) else {
        // Permissive: missing / malformed timestamps still surface.
        return true;
    };
    parsed.with_timezone(&Utc) >= cutoff
}

fn event_actors(e: &TimelineEvent) -> Vec<String> {
    let mut out: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    if !e.actor.is_empty() {
        out.insert(e.actor.clone());
    }
    for a in &e.actors {
        if !a.is_empty() {
            out.insert(a.clone());
        }
    }
    if let Some(map) = e.refs.as_object() {
        if let Some(arr) = map.get("people").and_then(|v| v.as_array()) {
            for v in arr {
                if let Some(s) = v.as_str() {
                    if !s.is_empty() {
                        out.insert(s.to_string());
                    }
                }
            }
        }
    }
    out.into_iter().collect()
}

fn event_threads(e: &TimelineEvent) -> Vec<String> {
    let mut out: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    if let Some(map) = e.refs.as_object() {
        if let Some(arr) = map.get("threads").and_then(|v| v.as_array()) {
            for v in arr {
                if let Some(s) = v.as_str() {
                    if !s.is_empty() {
                        out.insert(s.to_string());
                    }
                }
            }
        }
    }
    out.into_iter().collect()
}

/// Tags = `refs.tags` array if present, else falls back to the
/// `concepts` field. Used by both decisions (primary tag) and people
/// (top-3 tag aggregation).
fn event_tags(e: &TimelineEvent) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    if let Some(map) = e.refs.as_object() {
        if let Some(arr) = map.get("tags").and_then(|v| v.as_array()) {
            for v in arr {
                if let Some(s) = v.as_str() {
                    if !s.is_empty() {
                        out.push(s.to_string());
                    }
                }
            }
        }
    }
    if out.is_empty() {
        for c in &e.concepts {
            if !c.is_empty() {
                out.push(c.clone());
            }
        }
    }
    out
}

fn primary_tag(e: &TimelineEvent) -> String {
    let tags = event_tags(e);
    if tags.is_empty() {
        e.kind.clone()
    } else {
        format!("#{}", tags[0])
    }
}

fn relative_ago(ts: Option<&str>, now: DateTime<Utc>) -> String {
    let Some(ts) = ts else {
        return "?".to_string();
    };
    let Ok(parsed) = DateTime::parse_from_rfc3339(ts) else {
        return "?".to_string();
    };
    let elapsed = now.signed_duration_since(parsed.with_timezone(&Utc));
    if elapsed.num_minutes() < 1 {
        return "<1m ago".to_string();
    }
    if elapsed.num_minutes() < 60 {
        return format!("{}m ago", elapsed.num_minutes());
    }
    if elapsed.num_hours() < 24 {
        return format!("{}h ago", elapsed.num_hours());
    }
    format!("{}d ago", elapsed.num_days())
}

// --------------------------------------------------------------------------
// Tests

#[cfg(test)]
mod tests {
    use super::*;

    fn ev(id: &str, ts: &str, actor: &str, kind: &str, body: &str) -> TimelineEvent {
        TimelineEvent {
            id: id.to_string(),
            ts: ts.to_string(),
            source: "claude_code".to_string(),
            actor: actor.to_string(),
            actors: vec![],
            kind: kind.to_string(),
            refs: serde_json::json!({}),
            status: "active".to_string(),
            file: None,
            line: None,
            body: Some(body.to_string()),
            lifecycle: None,
            sample: false,
            confidence: 1.0,
            concepts: vec![],
            alternatives: vec![],
            source_count: 1,
        }
    }

    fn ev_with_refs(
        id: &str,
        ts: &str,
        actor: &str,
        kind: &str,
        body: &str,
        refs: serde_json::Value,
        source: &str,
    ) -> TimelineEvent {
        let mut e = ev(id, ts, actor, kind, body);
        e.refs = refs;
        e.source = source.to_string();
        e
    }

    fn now() -> DateTime<Utc> {
        DateTime::parse_from_rfc3339("2026-04-29T12:00:00Z")
            .unwrap()
            .with_timezone(&Utc)
    }

    #[test]
    fn empty_events_emit_honest_stub() {
        let body = build_team_index_markdown(&[], now());
        assert!(body.starts_with(SENTINEL));
        assert!(body.contains("0 atoms scanned"));
        assert!(body.contains("No atoms captured yet"));
    }

    #[test]
    fn sample_only_events_emit_stub() {
        let mut e = ev(
            "evt-2026-04-29-aaa1112222",
            "2026-04-29T11:30:00Z",
            "daizhe",
            "decision",
            "x",
        );
        e.sample = true;
        let body = build_team_index_markdown(&[e], now());
        assert!(body.contains("0 atoms scanned"));
        assert!(body.contains("No atoms captured yet"));
    }

    #[test]
    fn decisions_filter_keeps_recent_decision_kinds() {
        let evs = vec![
            ev_with_refs(
                "evt-2026-04-29-aaa1112222",
                "2026-04-29T11:00:00Z",
                "daizhe",
                "decision",
                "Pin gateway to RK3588",
                serde_json::json!({ "tags": ["pcb"] }),
                "claude_code",
            ),
            ev(
                "evt-2026-04-29-bbb1112222",
                "2026-04-29T10:00:00Z",
                "daizhe",
                "meeting_chunk", // not a decision
                "transcript blob",
            ),
            // Stale decision (10 days old) — excluded by the 7-day window.
            ev(
                "evt-2026-04-19-ccc1112222",
                "2026-04-19T10:00:00Z",
                "daizhe",
                "decision",
                "old call",
            ),
        ];
        let body = build_team_index_markdown(&evs, now());
        // Slice out just the "Recent decisions" section so we can assert
        // on its specific contents (the meeting_chunk legitimately
        // appears in the "Recent atoms" 24h slice).
        let dec_start = body
            .find("## Recent decisions")
            .expect("decisions header present");
        let dec_end = body[dec_start..]
            .find("\n## ")
            .map(|i| dec_start + i)
            .unwrap_or(body.len());
        let dec = &body[dec_start..dec_end];
        assert!(dec.contains("Pin gateway to RK3588"));
        assert!(!dec.contains("transcript blob"));
        assert!(!dec.contains("old call"));
        assert!(dec.contains("[#pcb]"));
    }

    #[test]
    fn threads_grouping_aggregates_by_topic() {
        let evs = vec![
            ev_with_refs(
                "evt-2026-04-29-aaa1112222",
                "2026-04-29T11:30:00Z",
                "daizhe",
                "meeting_chunk",
                "first ping",
                serde_json::json!({ "threads": ["pricing"], "people": ["hongyu"] }),
                "discord",
            ),
            ev_with_refs(
                "evt-2026-04-29-bbb1112222",
                "2026-04-29T11:55:00Z",
                "hongyu",
                "meeting_chunk",
                "latest reply",
                serde_json::json!({ "threads": ["pricing"], "people": ["sam"] }),
                "discord",
            ),
            ev_with_refs(
                "evt-2026-04-29-ccc1112222",
                "2026-04-29T08:00:00Z",
                "sam",
                "meeting_chunk",
                "off-topic",
                serde_json::json!({ "threads": ["pcb"] }),
                "github",
            ),
        ];
        let body = build_team_index_markdown(&evs, now());
        // pricing thread should appear with 2 atoms + members include
        // daizhe, hongyu, sam.
        assert!(body.contains("2 atoms"));
        assert!(body.contains("@daizhe"));
        assert!(body.contains("@hongyu"));
        assert!(body.contains("\"latest reply\""));
        // pcb thread (1 atom) also surfaces.
        assert!(body.contains("1 atoms"));
    }

    #[test]
    fn people_aggregation_counts_actors_and_top_tags() {
        let evs = vec![
            ev_with_refs(
                "evt-2026-04-29-aaa1112222",
                "2026-04-29T11:30:00Z",
                "daizhe",
                "meeting_chunk",
                "x",
                serde_json::json!({ "tags": ["pcb", "gtm"] }),
                "cursor",
            ),
            ev_with_refs(
                "evt-2026-04-29-bbb1112222",
                "2026-04-29T11:00:00Z",
                "daizhe",
                "meeting_chunk",
                "y",
                serde_json::json!({ "tags": ["pcb"] }),
                "claude_code",
            ),
            // Stale (older than 24h) — excluded.
            ev(
                "evt-2026-04-27-ccc1112222",
                "2026-04-27T11:00:00Z",
                "stale",
                "meeting_chunk",
                "z",
            ),
        ];
        let body = build_team_index_markdown(&evs, now());
        assert!(body.contains("daizhe"));
        assert!(body.contains("cursor"));
        assert!(body.contains("claude_code"));
        assert!(body.contains("2 atoms"));
        // pcb appears in 2 atoms → first in top-tags ranking.
        assert!(body.contains("top tags: pcb, gtm"));
        assert!(!body.contains("- stale "));
    }

    #[test]
    fn recent_atoms_truncates_body_to_80_chars() {
        let long =
            "this is a very long body line that absolutely should be truncated to fit in the recent atoms section because we cap at eighty characters";
        let evs = vec![ev(
            "evt-2026-04-29-aaa1112222",
            "2026-04-29T11:55:00Z",
            "daizhe",
            "meeting_chunk",
            long,
        )];
        let body = build_team_index_markdown(&evs, now());
        // The trimmed body in "Recent atoms" line cannot exceed ~80 chars
        // followed by ellipsis. A simple invariant: every line in the
        // file is shorter than the full original body.
        for line in body.lines().filter(|l| l.starts_with("- 11:55 daizhe")) {
            assert!(line.contains("…"));
            assert!(line.len() < long.len() + 40);
        }
    }

    #[test]
    fn ten_kb_cap_truncates_recent_atoms_first() {
        // Generate 200 atoms with long bodies to bust the 10 KB cap.
        let mut evs: Vec<TimelineEvent> = Vec::new();
        for i in 0..200u32 {
            let body = format!("decision body number {i} with a moderate amount of explanatory text");
            evs.push(ev(
                &format!("evt-2026-04-29-{:010x}", i),
                "2026-04-29T11:55:00Z",
                "daizhe",
                "meeting_chunk",
                &body,
            ));
        }
        let body = build_team_index_markdown(&evs, now());
        assert!(
            body.len() <= HARD_CEILING_BYTES,
            "body length {} exceeded ceiling {}",
            body.len(),
            HARD_CEILING_BYTES
        );
        // The header sections must still be intact.
        assert!(body.contains("Recent decisions"));
        assert!(body.contains("Active threads"));
        assert!(body.contains("Who's been active"));
    }

    #[test]
    fn write_team_index_to_round_trips_disk() {
        let dir = std::env::temp_dir().join(format!(
            "tg_team_index_{}",
            uuid::Uuid::new_v4().simple()
        ));
        std::fs::create_dir_all(dir.join(".tangerine")).unwrap();
        // Write a 1-event timeline.json so load_all_events returns 1.
        let payload = serde_json::json!({
            "version": 1,
            "events": [{
                "id": "evt-2026-04-29-aaa1112222",
                "ts": "2026-04-29T11:55:00Z",
                "source": "claude_code",
                "actor": "daizhe",
                "actors": ["daizhe"],
                "kind": "decision",
                "refs": { "tags": ["pcb"] },
                "status": "active",
                "body": "Pin gateway to RK3588"
            }],
            "vector_store": { "type": "none", "dimensions": null, "model": null }
        });
        std::fs::write(
            dir.join(".tangerine").join("timeline.json"),
            serde_json::to_string(&payload).unwrap(),
        )
        .unwrap();

        let out = write_team_index_to(&dir).expect("write succeeded");
        assert_eq!(out.atoms_scanned, 1);
        assert!(out.bytes_written > 0);
        let written = std::fs::read_to_string(dir.join("TEAM_INDEX.md")).unwrap();
        assert!(written.starts_with(SENTINEL));
        assert!(written.contains("Pin gateway to RK3588"));
        assert!(written.contains("[#pcb]"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn write_team_index_to_writes_stub_when_empty() {
        let dir = std::env::temp_dir().join(format!(
            "tg_team_index_empty_{}",
            uuid::Uuid::new_v4().simple()
        ));
        // Don't create .tangerine or timeline.json — empty memory dir.
        let out = write_team_index_to(&dir).expect("write succeeded");
        assert_eq!(out.atoms_scanned, 0);
        let written = std::fs::read_to_string(dir.join("TEAM_INDEX.md")).unwrap();
        assert!(written.contains("No atoms captured yet"));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
