import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { ChevronDown, ChevronRight, Calendar, Check } from "lucide-react";
import { Button } from "@/components/ui/button";

/**
 * Top-of-page daily brief card on /today.
 *
 * Reads markdown from `<memory>/.tangerine/briefs/<YYYY-MM-DD>.md`
 * generated by the daemon's `brief-generator` extension once per day after
 * 8 AM local. Collapsible — defaults to expanded the first time the user
 * sees today's brief, collapsed once they hit "Mark read".
 *
 * "Mark read" calls a parent-supplied callback. The parent is responsible
 * for calling mark_atom_acked on the brief atom id (Stage 2 atoms_acked
 * will drive personalization — Stage 1 just persists the ack).
 */
export function DailyBriefCard({
  date,
  markdown,
  exists,
  generatedAt,
  acked,
  onMarkRead,
}: {
  date: string;
  markdown: string | null;
  exists: boolean;
  generatedAt?: string | null;
  acked?: boolean;
  onMarkRead?: () => void;
}) {
  const [collapsed, setCollapsed] = useState(false);

  if (!exists || !markdown) {
    return (
      <section
        data-daily-brief-card
        className="mb-6 rounded-md border border-dashed border-stone-300 bg-stone-50/40 p-5 dark:border-stone-700 dark:bg-stone-900/40"
      >
        <p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-stone-500 dark:text-stone-400">
          <Calendar size={11} />
          Daily brief
        </p>
        <p className="mt-3 text-[12px] leading-relaxed text-stone-500 dark:text-stone-400">
          Tangerine writes today's brief once it has captured something to
          summarise. Brief generation runs daily after 8 AM local.
        </p>
      </section>
    );
  }

  return (
    <section
      data-daily-brief-card
      className="mb-6 rounded-md border border-stone-200 bg-stone-50 p-5 dark:border-stone-800 dark:bg-stone-900"
    >
      <div className="flex items-center gap-2">
        <button
          type="button"
          onClick={() => setCollapsed((c) => !c)}
          className="flex items-center gap-1.5 text-stone-700 hover:text-stone-900 dark:text-stone-300 dark:hover:text-stone-100"
          aria-expanded={!collapsed}
          aria-label={collapsed ? "Expand daily brief" : "Collapse daily brief"}
        >
          {collapsed ? <ChevronRight size={12} /> : <ChevronDown size={12} />}
          <Calendar size={12} className="text-stone-500" />
          <span className="text-[11px] font-semibold uppercase tracking-wider text-stone-500 dark:text-stone-400">
            Daily brief
          </span>
        </button>
        <span className="font-mono text-[11px] text-stone-500 dark:text-stone-400">
          {date}
          {generatedAt && (
            <span className="ml-2 text-stone-400 dark:text-stone-500">
              · written {formatGenerated(generatedAt)}
            </span>
          )}
        </span>
        <div className="ml-auto">
          {acked ? (
            <span className="inline-flex items-center gap-1 font-mono text-[11px] text-emerald-700 dark:text-emerald-400">
              <Check size={11} /> read
            </span>
          ) : (
            <Button
              variant="outline"
              size="sm"
              onClick={onMarkRead}
              className="text-[11px]"
            >
              Mark read
            </Button>
          )}
        </div>
      </div>
      {!collapsed && (
        <div className="prose-tangerine mt-4">
          <ReactMarkdown
            components={{
              h1: ({ children }) => (
                <h1 className="font-display text-xl tracking-tight text-stone-900 dark:text-stone-100">
                  {children}
                </h1>
              ),
              h2: ({ children }) => (
                <h2 className="mt-4 font-display text-base tracking-tight text-stone-900 dark:text-stone-100">
                  {children}
                </h2>
              ),
              h3: ({ children }) => (
                <h3 className="mt-3 text-[13px] font-medium text-stone-900 dark:text-stone-100">
                  {children}
                </h3>
              ),
              p: ({ children }) => (
                <p className="mt-2 text-[13px] leading-relaxed text-stone-700 dark:text-stone-300">
                  {children}
                </p>
              ),
              ul: ({ children }) => (
                <ul className="mt-2 list-disc space-y-1 pl-5 text-[13px] text-stone-700 dark:text-stone-300">
                  {children}
                </ul>
              ),
              ol: ({ children }) => (
                <ol className="mt-2 list-decimal space-y-1 pl-5 text-[13px] text-stone-700 dark:text-stone-300">
                  {children}
                </ol>
              ),
              code: ({ children }) => (
                <code className="rounded bg-stone-100 px-1 py-0.5 font-mono text-[11px] text-stone-900 dark:bg-stone-800 dark:text-stone-100">
                  {children}
                </code>
              ),
            }}
          >
            {markdown}
          </ReactMarkdown>
        </div>
      )}
    </section>
  );
}

function formatGenerated(iso: string): string {
  const t = Date.parse(iso);
  if (Number.isNaN(t)) return "recently";
  const seconds = Math.max(0, Math.floor((Date.now() - t) / 1000));
  if (seconds < 60) return "just now";
  if (seconds < 60 * 60) return `${Math.floor(seconds / 60)} min ago`;
  if (seconds < 60 * 60 * 24) return `${Math.floor(seconds / 3600)} hr ago`;
  return `${Math.floor(seconds / (60 * 60 * 24))} d ago`;
}
